variables:
    CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH
    DOCKER_DRIVER: overlay2

stages:
    - build

build:
    stage: build
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build --compress --cache-from $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME -t $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME -f Dockerfile .
        - docker tag $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME $CONTAINER_IMAGE:latest
        - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME
        - docker push $CONTAINER_IMAGE:latest
